name: sds_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-250.0.dev

# Add regular dependencies here.
dependencies:
  postgres: ^3.5.0
  image_v3: ^3.3.0
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
