name: sds_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-250.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  intl: ^0.19.0
  http: ^1.3.0

  flutter_localizations:
    sdk: flutter
  file_picker: ^8.3.2
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  fonts:
    - family: Arial
      fonts:
        - asset: fonts/ARIAL.TTF
        - asset: fonts/ARIALBD.TTF
          weight: 700
        - asset: fonts/ARIALBI.TTF
          weight: 700
          style: italic
        - asset: fonts/ARIALI.TTF
          style: italic

  uses-material-design: true

  # assets:
  #   - assets/
